Algoritmo "Exercício 6 (Fluxograma)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
n1,n2,n3,soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero:")
Leia(n1)
Escreval("Digite um numero:")
Leia(n2)
Escreval("Digite um numero:")
Leia(n3)
soma <- n1+n2
se soma <n3 entao
escreval("Forma um triangulo")
senao
escreval("Não forma um triangulo")
fimse


Fimalgoritmo