Algoritmo "Exercício 4 (Fluxograma)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
N, S, X: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número:")
Leia(N)
Para X  de 1 ate N faça
S <- S+X
fimpara
Escreval("Soma é:",S)

Fimalgoritmo