Algoritmo "Exercício 5 (Fluxograma)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite a idade:")
Leia(idade)
Se idade >= 65 entao
escreval("Idoso")
senao
 se idade >=18 entao
 escreval("Maior de Idade")
 senao
 escreval ("Menor de idade")
 fimse
fimse

Fimalgoritmo